version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - fastapi_uploads:/app/upload
    environment:
      HOST: lasan.digital  

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      SENDER_USER: limahaliyana@gmail.com
      SENDER_PW: hyf7VwcB9JEZSOAX
      NEXT_PUBLIC_API_URL: http://lasan.digital/api/


volumes:
  fastapi_uploads:
