services:
  fastapi:
    image: kidfromjupiter/personal:portfolio-backend
    ports:
      - "8000:8000"
    volumes:
      - fastapi_uploads:/app/upload
    environment:
      HOSTNAME: lasan.digital
    restart: unless-stopped

  nextjs:
    image: kidfromjupiter/personal:portfolio-frontend
    ports:
      - "3000:3000"
    environment:
      SENDER_USER: limahaliyana@gmail.com
      SENDER_PW: hyf7VwcB9JEZSOAX
    restart: unless-stopped

volumes:
  fastapi_uploads:
