services:
  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - fastapi_uploads:/app/upload
    environment:
      HOSTNAME: lasan.digital  

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://lasan.digital/api/
    ports:
      - "3000:3000"
    environment:
      SENDER_USER: limahaliyana@gmail.com
      SENDER_PW: hyf7VwcB9JEZSOAX


volumes:
  fastapi_uploads:
